Add sync status to message history
glifio/react-components pull request #467
Opened 2022-07-08 22:20 UTC by Schwartz10

2022-07-11 10:01 UTC, navFooh requested changes

2022-07-11 10:01 UTC, navFooh commented on src/components/SyncStatus/index.tsx
> +        setChainHead(subscriptionData.data?.chainHead?.height as number)
`subscriptionData.data?.chainHead?.height` should already be correctly interpreted as `number`. I think it's best not to overwrite the type derived from the GraphQL schema, so TypeScript will correctly warn us of any changes.

2022-07-11 10:01 UTC, navFooh commented on src/components/SyncStatus/index.tsx
> +    shouldResubscribe: chainHead === 0,
Why do we need to resubscribe here?

2022-07-11 10:01 UTC, navFooh commented on src/components/SyncStatus/index.tsx
> +  }, [data?.status?.height, chainHead])
Both `data?.status?.height` and `chainHead` are of type `number`, so there should be no reason to convert to `BigNumber` in this calculation. Also, `toFixed()` returns a string and the default return value is a number, which is not the best practice. That's why I'd prefer to always add the generic type to `useMemo`, so typescript will catch inconsistencies or at least make it obvious when there are different return types (`<string | number>`).

2022-07-11 10:01 UTC, navFooh commented on src/components/SyncStatus/index.tsx
> +      {syncPercentage > 0 && (
Checking `syncPercentage  > 0` is not the best since `syncPercentage` can be a string

2022-07-11 10:01 UTC, navFooh commented on src/components/SyncStatus/index.tsx
> +  }, [data?.status?.height, chainHead])
I'd rather do something like `Math.round((chainHead - data?.status?.height) / chainHead * 100)` to get an even number, potentially wrap it in `Math.min(100, Math.max(0, ...))` to ensure it's never less than `0` or more than `100`.

2022-07-13 16:23 UTC, Schwartz10 commented on src/components/SyncStatus/index.tsx
> +    shouldResubscribe: chainHead === 0,
The server can sometimes drop connection with the filecoin node, which then drops the connection from the web app client to the server. If that happens and we haven't got the data, we should resub

2022-07-13 17:53 UTC, navFooh commented on src/components/SyncStatus/index.tsx
> +    shouldResubscribe: chainHead === 0,
I see, that makes sense.

Reading the documentation for `shouldResubscribe`, it doesn't make it obvious to me that this option works that way:
> Determines if your subscription should be unsubscribed and subscribed again

This rather tells me, "when this value is / becomes truthy, stop and restart the connection", not "when the connection drops, resubscribe if this value is truthy".

The latter should happen by default I imagine. Though if you're sure that this works as intended, it's good for me

2022-07-14 16:06 UTC, Schwartz10 commented on src/components/SyncStatus/index.tsx
> +    shouldResubscribe: chainHead === 0,
Ah yeah maybe i'm misunderstanding... The documentation for `shouldResubscribe` isn't super helpful, but i found this comment https://github.com/apollographql/apollo-client/issues/7511#issuecomment-768093125 which (could be wrong) says that shouldResubscribe is default true. If anything, this at least says _dont_ resubscribe (for whatever reason we were unsubbed in the first place..) if we already have the data.

2022-07-14 16:06 UTC, Schwartz10 commented on src/components/SyncStatus/index.tsx
> +    shouldResubscribe: chainHead === 0,
I'll keep it for now and if we notice bandwidth going crazy on the backend or something, we can try disabling

2022-07-14 16:09 UTC, Schwartz10 commented on src/components/SyncStatus/index.tsx
> +      {syncPercentage > 0 && (
After the changes, doesn't seem like syncPercentage will ever be a string, so will keep this for now

2022-07-14 16:18 UTC, navFooh commented on src/components/SyncStatus/index.tsx
> +    shouldResubscribe: chainHead === 0,
sounds good!

2022-07-14 16:19 UTC, navFooh approved these changes

2022-07-14 16:28 UTC, merged